#!/usr/bin/env bash
#
# Runs the module's `terraform test` suite against every azurerm provider major
# the module claims to support. terraform.tf pins ">= 4, < 6", so the module
# must work under both azurerm 4.x and 5.x.
#
# `terraform init` resolves a single provider version per working directory, so
# each major is pinned for one run via a temporary `*_override.tf` file (which
# overrides the version constraint in terraform.tf) and the suite is executed
# once per major.
#
# Usage:
#   tests/provider-version-matrix.sh        # test azurerm 4.x and 5.x
#   tests/provider-version-matrix.sh 5      # test only azurerm 5.x
#
# The tests use `mock_provider "azurerm"`, so no Azure credentials are required.
#
set -euo pipefail

# Run from the module root regardless of the caller's working directory.
cd "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

override="provider_version_override.tf"
cleanup() { rm -f "$override"; }
trap cleanup EXIT

majors=("$@")
if [ "${#majors[@]}" -eq 0 ]; then
  majors=(4 5)
fi

rc=0
for major in "${majors[@]}"; do
  printf '\n==> azurerm ~> %s.0\n' "$major"

  cat > "$override" <<EOF
# Generated by tests/provider-version-matrix.sh to pin the azurerm major for a
# single test run. Safe to delete; git-ignored.
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> ${major}.0"
    }
  }
}
EOF

  terraform init -upgrade -no-color >/dev/null
  terraform version | awk '/provider.*azurerm/ { print "    using " $0 }'

  if terraform test -no-color; then
    printf '==> azurerm %s.x: PASS\n' "$major"
  else
    printf '==> azurerm %s.x: FAIL\n' "$major"
    rc=1
  fi
done

printf '\n'
if [ "$rc" -eq 0 ]; then
  echo "All provider majors passed."
else
  echo "One or more provider majors failed."
fi
exit "$rc"
